- Verb:
    id: http://www.purl.org/ogit/configures
    name: configures
    description: |
      The `from` entity, contains configuration data for the to `entity`

    admin-contact: arago GmbH
    tech-contact: arago GmbH
    created: 2015-04-27
    creator: cwalker@arago.de
    deleter:
    modified: 2015-04-27
    valid-from: 2015-04-27
    valid-until:
    allowed:
      - from: http://www.purl.org/ogit/Forum/Configuration
        to: http://www.purl.org/ogit/Forum/Profile

    history:
      - id: 1
        date: 2015-04-27
        description: intitial inception
        modified-by: cwalker@arago.de
